### ISSUE TITLE
Add better check style and code formatting

### ISSUE THREAD

**Issue by chombium** [eclipse/ponte#29]
Add better check style and code formatting based on ESLint and refactor the souce code to reflect the changes

**Comment by chombium** [comment]
Browsing the source code of [aedes](https://github.com/mcollina/aedes) mentioned by @mcollina  in #32 I noticed that he used [StandardJS](http://standardjs.com/) for the project. 
JSStandard looks really nice and since it works out of the box  and there are no configuration files to maintain and adjust. I think it would be better option

**Comment by mcollina** [comment]
That's my idea :)

**Comment by chombium** [comment]
I added StandardJS and reformatted the code to conform it's rules. I will create one big pull request together with the changes for #28 and #30 when I'm finished

**Comment by chombium** [comment]
The changes have been merged into the master
