### ISSUE TITLE
problem with mongodb connection

### ISSUE THREAD

**Issue by sumitsaurav113** [eclipse/ponte#33]
how to connect mongoDB  and authentication in ponte?? 
i am not getting documentation. Can u give the solution ..

**Comment by chombium** [comment]
Hi @sumitsaurav113, 
Please check the following link for example confiiguration. https://github.com/eclipse/ponte/blob/master/test/sample_config_mongodb.js

Ponte uses [Mosca](https://github.com/mcollina/mosca) and Mosca uses the standard MongoDB [client](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html), so your connection url should have the following format:
```
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

HTH.

Best Regards,
Jovan

**Comment by sumitsaurav113** [comment]
where to keep the config.js file in ponte folder???
